AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Parent stack that deploys VPC, Amazon ECS cluster for AWS Fargate,
  and a serverless Amazon ECS service deployment that hosts
  the task containers on AWS Fargate

Parameters:
  ImageUrl:
    Type: String
    Default: public.ecr.aws/aws-containers/proton-demo-image:2d7f777
    Description:
      The url of a container image that contains the application process that
      will handle the traffic for this service

Resources:
  # The networking configuration. This creates an isolated
  # network specific to this particular environment
  VpcStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: vpc.yml

  # This stack contains the Amazon ECS cluster itself
  ClusterStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: cluster.yml

  # This stack contains the container deployment
  ServiceStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: service.yml
      Parameters:
        VpcId: !GetAtt VpcStack.Outputs.VpcId
        PublicSubnetIds: !GetAtt VpcStack.Outputs.PublicSubnetIds
        ClusterName: !GetAtt ClusterStack.Outputs.ClusterName
        ECSTaskExecutionRole: !GetAtt ClusterStack.Outputs.ECSTaskExecutionRole
        ImageUrl: !Ref ImageUrl

        # container settings
        ContainerCpu: 256
        ContainerMemory: 512
        ContainerPort: 8080
        DesiredCount: 1
        HealthCheckPath: /health

        # TODO: add envvars

Outputs:
  Endpoint:
    Description: The service endpoint
    Value: !GetAtt ServiceStack.Outputs.Endpoint
